### ISSUE TITLE
Adding via Nuget doesn't add reference to Nunit.Runners

### ISSUE THREAD

**Issue by neilkidd** [jole78/TeamCity.SpecFlow.Reporting#12]
Hi,

We are currently building specflow into our TeamCity pipeline, (many thanks).
The script failed when looking for NUnit.Runners in packages on the TeamCity server.
We fixed this by manually adding Nunit.Runners to the packages.config file in our project - could the package be changed to do this automatically alongside TeamCity.SpecFlow.Reporting ?

Regards,
Neil.

**Comment by jole78** [comment]
Sorry for the late response...I've been away for a while. I'll have a look and get back to you. /J

**Comment by Holf** [comment]
I have noticed the same behaviour. A work around is to add it manually.
