### ISSUE TITLE
No option to use x86 version of NUnit

### ISSUE THREAD

**Issue by Holf** [jole78/TeamCity.SpecFlow.Reporting#14]
The 'nunit-console.exe' NUnit Console Runner is called out in the TeamCity.SpecFlowReporting.psm1 script.

I have some tests where I need to use 'nunit-console-x86.exe' instead. I've been able to work around this by replacing the relevant string in TeamCity.SpecFlowReporting.psm1 but this is not ideal.

Ideally this would be configurable; I know it sort of is, via the PathToNUnitConsoleExe setting, but a simple 'UseX86NUnit' flag would be cool.

**Comment by jole78** [comment]
add it and issue a PR then...
